packaging_format = 2

id = "beatbump"
name = "Beatbump"
description.en = "Alternative YouTube Music frontend built with Svelte/SvelteKit"
description.fr = "Alternative YouTube Music frontend built with Svelte/SvelteKit"

version = "1.0~ynh1"

maintainers = [""]

[upstream]
license = "AGPL-3.0"
website = "https://beatbump.io/home"
demo = "https://beatbump.io/home"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/snuffyDev/Beatbump"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/snuffyDev/Beatbump/archive/refs/tags/v0.29.0.tar.gz"
        sha256 = "cbab32c2ffb7e76f9eb35020e7da624137340bb4559fd9fd3f73800d36cb33f5"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
